package com.springapp.mvc.model;

public class Basedata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.link
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.name
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.zsabbre
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String zsabbre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basedata.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Long zs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.id
     *
     * @return the value of basedata.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.id
     *
     * @param id the value for basedata.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.link
     *
     * @return the value of basedata.link
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.link
     *
     * @param link the value for basedata.link
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.name
     *
     * @return the value of basedata.name
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.name
     *
     * @param name the value for basedata.name
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.code
     *
     * @return the value of basedata.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.code
     *
     * @param code the value for basedata.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.zsabbre
     *
     * @return the value of basedata.zsabbre
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getZsabbre() {
        return zsabbre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.zsabbre
     *
     * @param zsabbre the value for basedata.zsabbre
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setZsabbre(String zsabbre) {
        this.zsabbre = zsabbre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basedata.zs
     *
     * @return the value of basedata.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Long getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basedata.zs
     *
     * @param zs the value for basedata.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setZs(Long zs) {
        this.zs = zs;
    }
}