package com.springapp.mvc.model;

import java.util.Date;

public class Fivem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.id
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.code
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.DAY
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.startp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double startp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.lastp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double lastp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.curp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double curp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.highp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double highp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.lowp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double lowp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.curbuyp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double curbuyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.curslp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double curslp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.curzs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long curzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.curamount
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double curamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long byonesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double byonep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.bytwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long bytwosh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.bytwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double bytwop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.bythreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long bythreesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.bythreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double bythreep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long byfoursh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double byfourp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long byfivesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.byfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double byfivep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long slonesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double slonep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.sltwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long sltwosh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.sltwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double sltwop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slthreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long slthreesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slthreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double slthreep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long slfoursh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double slfourp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long slfivesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.slfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double slfivep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.rate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.zs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Long zs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.hsrate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Double hsrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fivem.hang
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    private Boolean hang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.id
     *
     * @return the value of fivem.id
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.id
     *
     * @param id the value for fivem.id
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.code
     *
     * @return the value of fivem.code
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.code
     *
     * @param code the value for fivem.code
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.DAY
     *
     * @return the value of fivem.DAY
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.DAY
     *
     * @param day the value for fivem.DAY
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.startp
     *
     * @return the value of fivem.startp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getStartp() {
        return startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.startp
     *
     * @param startp the value for fivem.startp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setStartp(Double startp) {
        this.startp = startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.lastp
     *
     * @return the value of fivem.lastp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getLastp() {
        return lastp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.lastp
     *
     * @param lastp the value for fivem.lastp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setLastp(Double lastp) {
        this.lastp = lastp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.curp
     *
     * @return the value of fivem.curp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getCurp() {
        return curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.curp
     *
     * @param curp the value for fivem.curp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCurp(Double curp) {
        this.curp = curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.highp
     *
     * @return the value of fivem.highp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getHighp() {
        return highp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.highp
     *
     * @param highp the value for fivem.highp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setHighp(Double highp) {
        this.highp = highp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.lowp
     *
     * @return the value of fivem.lowp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getLowp() {
        return lowp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.lowp
     *
     * @param lowp the value for fivem.lowp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setLowp(Double lowp) {
        this.lowp = lowp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.curbuyp
     *
     * @return the value of fivem.curbuyp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getCurbuyp() {
        return curbuyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.curbuyp
     *
     * @param curbuyp the value for fivem.curbuyp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCurbuyp(Double curbuyp) {
        this.curbuyp = curbuyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.curslp
     *
     * @return the value of fivem.curslp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getCurslp() {
        return curslp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.curslp
     *
     * @param curslp the value for fivem.curslp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCurslp(Double curslp) {
        this.curslp = curslp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.curzs
     *
     * @return the value of fivem.curzs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getCurzs() {
        return curzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.curzs
     *
     * @param curzs the value for fivem.curzs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCurzs(Long curzs) {
        this.curzs = curzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.curamount
     *
     * @return the value of fivem.curamount
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getCuramount() {
        return curamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.curamount
     *
     * @param curamount the value for fivem.curamount
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setCuramount(Double curamount) {
        this.curamount = curamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byonesh
     *
     * @return the value of fivem.byonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getByonesh() {
        return byonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byonesh
     *
     * @param byonesh the value for fivem.byonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByonesh(Long byonesh) {
        this.byonesh = byonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byonep
     *
     * @return the value of fivem.byonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getByonep() {
        return byonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byonep
     *
     * @param byonep the value for fivem.byonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByonep(Double byonep) {
        this.byonep = byonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.bytwosh
     *
     * @return the value of fivem.bytwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getBytwosh() {
        return bytwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.bytwosh
     *
     * @param bytwosh the value for fivem.bytwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setBytwosh(Long bytwosh) {
        this.bytwosh = bytwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.bytwop
     *
     * @return the value of fivem.bytwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getBytwop() {
        return bytwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.bytwop
     *
     * @param bytwop the value for fivem.bytwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setBytwop(Double bytwop) {
        this.bytwop = bytwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.bythreesh
     *
     * @return the value of fivem.bythreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getBythreesh() {
        return bythreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.bythreesh
     *
     * @param bythreesh the value for fivem.bythreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setBythreesh(Long bythreesh) {
        this.bythreesh = bythreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.bythreep
     *
     * @return the value of fivem.bythreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getBythreep() {
        return bythreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.bythreep
     *
     * @param bythreep the value for fivem.bythreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setBythreep(Double bythreep) {
        this.bythreep = bythreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byfoursh
     *
     * @return the value of fivem.byfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getByfoursh() {
        return byfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byfoursh
     *
     * @param byfoursh the value for fivem.byfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByfoursh(Long byfoursh) {
        this.byfoursh = byfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byfourp
     *
     * @return the value of fivem.byfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getByfourp() {
        return byfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byfourp
     *
     * @param byfourp the value for fivem.byfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByfourp(Double byfourp) {
        this.byfourp = byfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byfivesh
     *
     * @return the value of fivem.byfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getByfivesh() {
        return byfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byfivesh
     *
     * @param byfivesh the value for fivem.byfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByfivesh(Long byfivesh) {
        this.byfivesh = byfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.byfivep
     *
     * @return the value of fivem.byfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getByfivep() {
        return byfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.byfivep
     *
     * @param byfivep the value for fivem.byfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setByfivep(Double byfivep) {
        this.byfivep = byfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slonesh
     *
     * @return the value of fivem.slonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getSlonesh() {
        return slonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slonesh
     *
     * @param slonesh the value for fivem.slonesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlonesh(Long slonesh) {
        this.slonesh = slonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slonep
     *
     * @return the value of fivem.slonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getSlonep() {
        return slonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slonep
     *
     * @param slonep the value for fivem.slonep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlonep(Double slonep) {
        this.slonep = slonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.sltwosh
     *
     * @return the value of fivem.sltwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getSltwosh() {
        return sltwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.sltwosh
     *
     * @param sltwosh the value for fivem.sltwosh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSltwosh(Long sltwosh) {
        this.sltwosh = sltwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.sltwop
     *
     * @return the value of fivem.sltwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getSltwop() {
        return sltwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.sltwop
     *
     * @param sltwop the value for fivem.sltwop
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSltwop(Double sltwop) {
        this.sltwop = sltwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slthreesh
     *
     * @return the value of fivem.slthreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getSlthreesh() {
        return slthreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slthreesh
     *
     * @param slthreesh the value for fivem.slthreesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlthreesh(Long slthreesh) {
        this.slthreesh = slthreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slthreep
     *
     * @return the value of fivem.slthreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getSlthreep() {
        return slthreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slthreep
     *
     * @param slthreep the value for fivem.slthreep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlthreep(Double slthreep) {
        this.slthreep = slthreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slfoursh
     *
     * @return the value of fivem.slfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getSlfoursh() {
        return slfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slfoursh
     *
     * @param slfoursh the value for fivem.slfoursh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlfoursh(Long slfoursh) {
        this.slfoursh = slfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slfourp
     *
     * @return the value of fivem.slfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getSlfourp() {
        return slfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slfourp
     *
     * @param slfourp the value for fivem.slfourp
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlfourp(Double slfourp) {
        this.slfourp = slfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slfivesh
     *
     * @return the value of fivem.slfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getSlfivesh() {
        return slfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slfivesh
     *
     * @param slfivesh the value for fivem.slfivesh
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlfivesh(Long slfivesh) {
        this.slfivesh = slfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.slfivep
     *
     * @return the value of fivem.slfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getSlfivep() {
        return slfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.slfivep
     *
     * @param slfivep the value for fivem.slfivep
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setSlfivep(Double slfivep) {
        this.slfivep = slfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.rate
     *
     * @return the value of fivem.rate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.rate
     *
     * @param rate the value for fivem.rate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.zs
     *
     * @return the value of fivem.zs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Long getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.zs
     *
     * @param zs the value for fivem.zs
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setZs(Long zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.hsrate
     *
     * @return the value of fivem.hsrate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Double getHsrate() {
        return hsrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.hsrate
     *
     * @param hsrate the value for fivem.hsrate
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setHsrate(Double hsrate) {
        this.hsrate = hsrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fivem.hang
     *
     * @return the value of fivem.hang
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public Boolean getHang() {
        return hang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fivem.hang
     *
     * @param hang the value for fivem.hang
     *
     * @mbggenerated Sat Oct 31 21:41:23 CST 2015
     */
    public void setHang(Boolean hang) {
        this.hang = hang;
    }
}