package com.springapp.mvc.model;

import java.util.Date;

public class Hsrate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.id
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.code
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.DATE
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.rate
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.curs
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Long curs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.curp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Double curp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.prevp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Double prevp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsrate.totalr
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    private Double totalr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.id
     *
     * @return the value of hsrate.id
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.id
     *
     * @param id the value for hsrate.id
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.code
     *
     * @return the value of hsrate.code
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.code
     *
     * @param code the value for hsrate.code
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.DATE
     *
     * @return the value of hsrate.DATE
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.DATE
     *
     * @param date the value for hsrate.DATE
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.rate
     *
     * @return the value of hsrate.rate
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.rate
     *
     * @param rate the value for hsrate.rate
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.curs
     *
     * @return the value of hsrate.curs
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Long getCurs() {
        return curs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.curs
     *
     * @param curs the value for hsrate.curs
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setCurs(Long curs) {
        this.curs = curs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.curp
     *
     * @return the value of hsrate.curp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Double getCurp() {
        return curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.curp
     *
     * @param curp the value for hsrate.curp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setCurp(Double curp) {
        this.curp = curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.prevp
     *
     * @return the value of hsrate.prevp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Double getPrevp() {
        return prevp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.prevp
     *
     * @param prevp the value for hsrate.prevp
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setPrevp(Double prevp) {
        this.prevp = prevp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsrate.totalr
     *
     * @return the value of hsrate.totalr
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public Double getTotalr() {
        return totalr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsrate.totalr
     *
     * @param totalr the value for hsrate.totalr
     *
     * @mbggenerated Thu Oct 08 17:23:58 CST 2015
     */
    public void setTotalr(Double totalr) {
        this.totalr = totalr;
    }
}