package com.springapp.mvc.model;

import java.util.Date;

public class Owns {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer quan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.costp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double costp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owns.suggp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double suggp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.id
     *
     * @return the value of owns.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.id
     *
     * @param id the value for owns.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.code
     *
     * @return the value of owns.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.code
     *
     * @param code the value for owns.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.quan
     *
     * @return the value of owns.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getQuan() {
        return quan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.quan
     *
     * @param quan the value for owns.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setQuan(Integer quan) {
        this.quan = quan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.costp
     *
     * @return the value of owns.costp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getCostp() {
        return costp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.costp
     *
     * @param costp the value for owns.costp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setCostp(Double costp) {
        this.costp = costp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.day
     *
     * @return the value of owns.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.day
     *
     * @param day the value for owns.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owns.suggp
     *
     * @return the value of owns.suggp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getSuggp() {
        return suggp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owns.suggp
     *
     * @param suggp the value for owns.suggp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setSuggp(Double suggp) {
        this.suggp = suggp;
    }
}