package com.springapp.mvc.model;

import java.util.Date;

public class Price {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.startp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double startp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.END
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.high
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.low
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.hang
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Boolean hang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.prevp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double prevp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Long zs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.id
     *
     * @return the value of price.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.id
     *
     * @param id the value for price.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.startp
     *
     * @return the value of price.startp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getStartp() {
        return startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.startp
     *
     * @param startp the value for price.startp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setStartp(Double startp) {
        this.startp = startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.END
     *
     * @return the value of price.END
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.END
     *
     * @param end the value for price.END
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setEnd(Double end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.high
     *
     * @return the value of price.high
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.high
     *
     * @param high the value for price.high
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.low
     *
     * @return the value of price.low
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.low
     *
     * @param low the value for price.low
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.day
     *
     * @return the value of price.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.day
     *
     * @param day the value for price.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.hang
     *
     * @return the value of price.hang
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Boolean getHang() {
        return hang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.hang
     *
     * @param hang the value for price.hang
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setHang(Boolean hang) {
        this.hang = hang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.code
     *
     * @return the value of price.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.code
     *
     * @param code the value for price.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.prevp
     *
     * @return the value of price.prevp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getPrevp() {
        return prevp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.prevp
     *
     * @param prevp the value for price.prevp
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setPrevp(Double prevp) {
        this.prevp = prevp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.zs
     *
     * @return the value of price.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Long getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.zs
     *
     * @param zs the value for price.zs
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setZs(Long zs) {
        this.zs = zs;
    }
}