package com.springapp.mvc.model;

import java.util.Date;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.type
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer quan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.tradep
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Double tradep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.done
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Boolean done;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade.entrustno
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    private Integer entrustno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.id
     *
     * @return the value of trade.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.id
     *
     * @param id the value for trade.id
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.code
     *
     * @return the value of trade.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.code
     *
     * @param code the value for trade.code
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.type
     *
     * @return the value of trade.type
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.type
     *
     * @param type the value for trade.type
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.day
     *
     * @return the value of trade.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.day
     *
     * @param day the value for trade.day
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.quan
     *
     * @return the value of trade.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getQuan() {
        return quan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.quan
     *
     * @param quan the value for trade.quan
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setQuan(Integer quan) {
        this.quan = quan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.tradep
     *
     * @return the value of trade.tradep
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Double getTradep() {
        return tradep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.tradep
     *
     * @param tradep the value for trade.tradep
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setTradep(Double tradep) {
        this.tradep = tradep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.done
     *
     * @return the value of trade.done
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Boolean getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.done
     *
     * @param done the value for trade.done
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setDone(Boolean done) {
        this.done = done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade.entrustno
     *
     * @return the value of trade.entrustno
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public Integer getEntrustno() {
        return entrustno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade.entrustno
     *
     * @param entrustno the value for trade.entrustno
     *
     * @mbggenerated Mon Aug 17 20:54:01 CST 2015
     */
    public void setEntrustno(Integer entrustno) {
        this.entrustno = entrustno;
    }
}